### ISSUE TITLE
Property 'description' does not exist on type 'Asset'

### ISSUE THREAD

**Issue by tedawf** [nftscan-official/nftscan-api-js-sdk#12]
In `src/types/evm/asset/response-data.ts` there should be a property `description` since the method "Get NFTs by account" returns a response `content` of type `Asset`

![image](https://github.com/nftscan-official/nftscan-api-js-sdk/assets/17540318/927c6a10-fb9c-4bf5-93c2-f01e1473ee17)

**Comment by yohuohuohuo** [comment]
In fact, the value of the `description` field is centralized data obtained from markets such as OpenSea. If the market does not have this data, it is normal for the description to be empty.

**Comment by tedawf** [comment]
I mean in the file `/src/types/evm/asset/response-data.ts`, the `Asset` class does not have the `description : string` property field. This produces an typescript error that the property `description` does not exist on `Asset` but in fact it does exist. 

If the description can be empty, maybe it should be of type `description: string | null` ?

**Comment by yohuohuohuo** [comment]
OK, I got it. I will fix it in the next version. Thank you for pointing out the issue!

**Comment by yohuohuohuo** [comment]
This issue has been fixed, see https://github.com/nftscan-official/nftscan-api-js-sdk/commit/340db9caf281cd919e721055d49f92da9d5e2c28
