### ISSUE TITLE
Typescript issue: the multichain API data type

### ISSUE THREAD

**Issue by digital-flowers** [nftscan-official/nftscan-api-js-sdk#15]
I have notices that the typescript return data type of the `getMultiChainAssets` api is `Promise<QueryMultiChainAssets>` and the `QueryMultiChainAssets` data type is:

```
 {
    chain: string;
    collection_assets: Array<CollectionAssets>;
    exceed_max_items: boolean;
}
```
Which i think is incorrect and should be `Promise<QueryMultiChainAssets[]>` since you pass multiple chainIds.

Here is my test: 

<img width="383" alt="Screenshot 2023-07-18 at 10 01 15 PM" src="https://github.com/nftscan-official/nftscan-api-js-sdk/assets/5216291/b509e195-0e40-4120-9b26-a952c0386f9d">

**Comment by yohuohuohuo** [comment]
Thanks for pointing out the problem, I have fixed it, see https://github.com/nftscan-official/nftscan-api-js-sdk/commit/d86aa9b553c7345bbfe4f7fc3d9541920b036181
